name: Lotofácil API to MongoDB

on:
  workflow_dispatch: # Execução manual
  schedule:
    - cron: '0 15 * * *' # Executa todos os dias às 14h UTC

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalar dependências
      - name: Install dependencies
        run: |
          npm install axios mongodb

      # Obter dados da API da Lotofácil e salvar no MongoDB
      - name: Fetch Lotofácil data and save to MongoDB
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          node <<EOF
          const axios = require('axios');
          const { MongoClient } = require('mongodb');

          (async () => {
            try {
              // Fazer requisição para a API da Lotofácil
              const response = await axios.get(process.env.API_URL);
              const lotofacilData = response.data;

              // Conectar ao MongoDB Atlas
              const client = new MongoClient(process.env.MONGODB_URI);
              await client.connect();
              const db = client.db("loteria"); // Nome do banco
              const collection = db.collection("lotofacil"); // Nome da coleção

              // Inserir os dados no MongoDB
              await collection.insertMany(lotofacilData);
              console.log("Dados da Lotofácil inseridos com sucesso!");

              await client.close();
            } catch (error) {
              console.error("Erro ao salvar dados no MongoDB:", error.message);
              process.exit(1);
            }
          })();
          EOF
